version: '3.1'

services:

  db:
    image: mysql
    command: --init-file /application/mysql-server/scripts/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: beingzero
    volumes:
      - ./static-files/my_blog_db.sql:/application/mysql-server/scripts/init.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080